import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

// Define the base API service for authentication
export const authApi = createApi({
  reducerPath: 'authApi',
  baseQuery: fetchBaseQuery({
    baseUrl: 'https://your-api-url.com/api',
  }),
  endpoints: (builder) => ({
    login: builder.mutation({
      query: (credentials) => ({
        url: 'login',
        method: 'POST',
        body: credentials,
      }),
    }),
    // Additional authentication endpoints can be added here, such as register, logout, etc.
  }),
});

// Export hooks generated by the authApi
export const { useLoginMutation } = authApi;
